server:
  port: ${SERVER_PORT:8081}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: false

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.demo.consumer: DEBUG
    org.springframework.cloud.openfeign: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
